language: java
jdk:
  - oraclejdk8
script:
  - cd food-trip-back
  - chmod +x gradlew
  - ./gradlew test
cache:
  directories:
  - ~/.gradle
after_success:
  - ./food-trip-back/gradlew cobertura coveralls